export type IconType =
  | 'ImFacebook'
  | 'FaTwitter'
  | 'SiInstagram'
  | 'FaLinkedinIn'
  | 'ImSkype'
  | 'FaTumblr'
  | 'FaGoogle'
  | 'FaFacebookMessenger'
  | 'IoLogoWhatsapp'
  | 'FaQq'
  | 'ImPinterest'
  | 'AiFillYoutube'
  | 'GrVimeo'
  | 'IoLogoWechat'
  | 'GoMarkGithub'
  | 'FaDropbox'
  | 'FaSlackHash'
  | 'FaRedditAlien'
  | 'SiTiktok'
  | 'FaMicrosoft'
  | 'FaBehance'
  | 'FaWeibo'
  | 'FaTelegramPlane'
  | 'SiSnapchat'
  | 'FaQuora'
  | 'RiBilibiliFill'
  | 'FaPaypal'
  | 'FaMediumM'
  | 'FaYelp'
  | 'SiDribbble';

// export type IconDisplayType = 'Fill' | 'Line' | 'Outline';
