export type IconType =
  | 'ImFacebook'
  | 'FaTwitter'
  | 'GrInstagram'
  | 'FaLinkedinIn'
  | 'GrSkype'
  | 'FaTumblr'
  | 'GrGoogle'
  | 'FaFacebookMessenger'
  | 'IoLogoWhatsapp'
  | 'FaQq'
  | 'ImPinterest'
  | 'AiFillYoutube'
  | 'GrVimeo'
  | 'IoLogoWechat'
  | 'GoMarkGithub'
  | 'FaDropbox'
  | 'FaSlackHash'
  | 'FaRedditAlien'
  | 'SiTiktok'
  | 'FaMicrosoft'
  | 'GrApple'
  | 'FaWeibo'
  | 'FaTelegramPlane'
  | 'FaSnapchatGhost'
  | 'FaQuora'
  | 'RiBilibiliFill'
  | 'FaPaypal'
  | 'GrSoundcloud'
  | 'FaDiscord'
  | 'SiEvernote';

// export type IconDisplayType = 'Fill' | 'Line' | 'Outline';
